from __future__ import annotations

import os

MAX_JUPYTER_SESSIONS = 16
JUPYTER_SESSION_TIMEOUT_SECONDS = 1800
JUPYTER_KERNEL_READY_TIMEOUT_SECONDS = float(os.getenv("JUPYTER_KERNEL_READY_TIMEOUT_SECONDS", "30"))
